export const PATIENTS_MOCK_DATA = [
  {
    id: "d0d689db-9620-490e-a9b3-23327b43ed35",
    first_name: "Saidnurmuhammadulloxon",
    last_name: "Nasimxonov",
    phone_number: "+998991234567",
    gender: "male",
    birth_date: null,
  },
  {
    id: "P-1002",
    first_name: "Michael",
    last_name: "Chen",
    phone_number: "+1 (555) 987-6543",
    gender: "male",
    birth_date: "1979-05-15",
  },
  {
    id: "P-1003",
    first_name: "Emma",
    last_name: "Williams",
    phone_number: "+1 (555) 456-7890",
    gender: "female",
    birth_date: "1995-11-10",
  },
  {
    id: "P-1004",
    first_name: "David",
    last_name: "Smith",
    phone_number: "+1 (555) 234-5678",
    gender: "male",
    birth_date: "1972-03-20",
  },
  {
    id: "P-1005",
    first_name: "Jessica",
    last_name: "Davis",
    phone_number: "+1 (555) 876-5432",
    gender: "female",
    birth_date: "1983-01-05",
  },
];

export const APPOINTMENTS_MOCK_DATA = [
  {
    id: "APT-501",
    patientName: "Sarah Johnson",
    doctorName: "Dr. Robert Wilson",
    department: "Cardiology",
    date: "2024-03-25",
    time: "09:00 AM",
    type: "Follow-up",
    status: "Confirmed",
  },
  {
    id: "APT-502",
    patientName: "Michael Chen",
    doctorName: "Dr. Emily Brown",
    department: "Neurology",
    date: "2024-03-25",
    time: "10:30 AM",
    type: "Consultation",
    status: "Pending",
  },
  {
    id: "APT-503",
    patientName: "Emma Williams",
    doctorName: "Dr. James Taylor",
    department: "Orthopedics",
    date: "2024-03-26",
    time: "02:15 PM",
    type: "Check-up",
    status: "Confirmed",
  },
  {
    id: "APT-504",
    patientName: "David Smith",
    doctorName: "Dr. Lisa Anderson",
    department: "General Medicine",
    date: "2024-03-26",
    time: "04:00 PM",
    type: "Emergency",
    status: "Completed",
  },
  {
    id: "APT-505",
    patientName: "Jessica Davis",
    doctorName: "Dr. Robert Wilson",
    department: "Cardiology",
    date: "2024-03-27",
    time: "11:00 AM",
    type: "Consultation",
    status: "Cancelled",
  },
];
