services:
  vitalis-frontend:
    image: rayyandev/vitalis-frontend:latest

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://172.21.0.20:9000/api

    container_name: vitalis-frontend

    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://172.21.0.20:9000/api

    restart: unless-stopped
